name: Copilot | Accounting - Weekly load
description: Report weekly load for Copilot Accounting
title: "Load Submission"
labels: [
  "weekly-load",
  "Copilot | Accounting"
]

body:
  - type: input
    id: date
    attributes:
      label: "Date (monday for weekly)"
      description: "You can use the format dd/mm/yyyy or an ISO String"
      placeholder: "05/08/2024"
    validations:
      required: true

  - type: dropdown
    id: submission_type
    attributes:
      label: "Weekly or Daily submission"
      description: "You can decide to submit a whole week, or daily"
      multiple: false
      default: 0
      options:
        - "Weekly"
        - "Daily"
    validations:
      required: true

  - type: textarea
    id: product_workshop_announcements
    attributes:
      label: "Anything to announce at the Product workshop?"

  # Submission
  - id: support_load
    type: input
    attributes:
      label: "Support Load"

  - id: project_1_project
    type: dropdown
    attributes:
      label: "Project"
      multiple: false
      options: 
        - Project 1
        - Project 2
        - Project 3

  - id: project_1_load
    type: input
    attributes:
      label: "Load"
      description: "In dev.days. Reminder, 1 dev.day = 5hrs"

  - id: project_2_project
    type: dropdown
    attributes:
      label: "Project"
      multiple: false
      options: 
        - Project 1
        - Project 2
        - Project 3

  - id: project_2_load
    type: input
    attributes:
      label: "Load"
      description: "In dev.days. Reminder, 1 dev.day = 5hrs"
      
  - id: project_3_project
    type: dropdown
    attributes:
      label: "Project"
      multiple: false
      options: 
        - Project 1
        - Project 2
        - Project 3

  - id: project_3_load
    type: input
    attributes:
      label: "Load"
      description: "In dev.days. Reminder, 1 dev.day = 5hrs"
