name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit Tests

    steps:
      - uses: actions/checkout@master
      - run: npm i
      - run: npm test
